### ISSUE TITLE
KeyError: 'server_uri'

### ISSUE THREAD

**Issue by JaneFy** [flink-extended/ai-flow#106]
### Describe the bug

ubuntu 20.04
ai-flow 0.3.dev0

Traceback (most recent call last):
  File "./demo/workflows/simple_workflow/simple_workflow.py", line 27, in <module>
    main()
  File "./demo/workflows/simple_workflow/simple_workflow.py", line 6, in main
    af.init_ai_flow_context()
  File "/root/miniconda3/lib/python3.7/site-packages/ai_flow/api/ai_flow_context.py", line 46, in init_ai_flow_context
    ensure_project_registered()
  File "/root/miniconda3/lib/python3.7/site-packages/ai_flow/api/ai_flow_context.py", line 57, in ensure_project_registered
    client = get_ai_flow_client()
  File "/root/miniconda3/lib/python3.7/site-packages/ai_flow/client/ai_flow_client.py", line 61, in get_ai_flow_client
    current_uri = current_project_config().get_server_uri()
  File "/root/miniconda3/lib/python3.7/site-packages/ai_flow/project/project_config.py", line 31, in get_server_uri
    if len(self["server_uri"].split(',')) > 1 and not self.get_enable_ha():
KeyError: 'server_uri'

### To Reproduce
Steps to reproduce the behavior (if you can):
1. Submit a '...'
3. See error

**Comment by SteNicholas** [comment]
@JaneFy , thanks for your reporter of the simple workflow example. I couldn't reproduce the exception above mentioned. Could you please join the Dingding group for one to one troubleshoot?
