### ISSUE TITLE
Servers May Not Started When Client Access

### ISSUE THREAD

**Issue by jiangxin369** [flink-extended/ai-flow#195]
### Describe the bug
```

ai_flow_plugins/tests/it_workflows/workflows/test_bash/test_bash.py:64 (TestBash.test_bash_task)
self = <ai_flow_plugins.tests.it_workflows.workflows.test_bash.test_bash.TestBash testMethod=test_bash_task>

    def test_bash_task(self):
        def run_workflow(client: NotificationClient):
            with af.job_config('task_1'):
                af.user_define_operation(processor=bash.BashProcessor(bash_command='echo "Xiao ming hello world!"'))
            workflow_info = af.workflow_operation.submit_workflow(
                workflow_name=af.current_workflow_config().workflow_name)
            wei = af.workflow_operation.start_new_workflow_execution(
                workflow_name=af.current_workflow_config().workflow_name)
            set_workflow_execution_info(wei)
            while True:
                with create_session() as session:
                    dag_run = session.query(DagRun)\
                        .filter(DagRun.dag_id == 'test_project.{}'
                                .format(af.current_workflow_config().workflow_name)).first()
                    if dag_run is not None and dag_run.state == State.SUCCESS:
                        break
                    else:
                        time.sleep(1)
    
        run_ai_flow_workflow(dag_id=get_dag_id(af.current_project_config().get_project_name(),
                                               af.current_workflow_config().workflow_name),
>                            test_function=run_workflow)

test_bash.py:86: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../airflow_scheduler_utils.py:94: in run_ai_flow_workflow
    start_scheduler(file_path=dag_file, port=port, executor=executor)
../../../airflow_scheduler_utils.py:42: in start_scheduler
    refresh_dag_dir_interval=30
<string>:4: in __init__
    ???
../../../../../../venv/lib/python3.7/site-packages/sqlalchemy/orm/state.py:433: in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
../../../../../../venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py:70: in __exit__
    with_traceback=exc_tb,
../../../../../../venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py:182: in raise_
    raise exception
../../../../../../venv/lib/python3.7/site-packages/sqlalchemy/orm/state.py:430: in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
../../../../../../venv/lib/python3.7/site-packages/airflow/contrib/jobs/event_based_scheduler_job.py:659: in __init__
    default_namespace=SCHEDULER_NAMESPACE)
../../../../../../venv/lib/python3.7/site-packages/notification_service/client.py:178: in __init__
    response = self.notification_stub.registerClient(request)
../../../../../../venv/lib/python3.7/site-packages/grpc/_channel.py:923: in __call__
    return _end_unary_response_blocking(state, call, False, None)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

state = <grpc._channel._RPCState object at 0x7f989332b2d0>
call = <grpc._cython.cygrpc.SegregatedCall object at 0x7f9898e15a00>
with_call = False, deadline = None

    def _end_unary_response_blocking(state, call, with_call, deadline):
        if state.code is grpc.StatusCode.OK:
            if with_call:
                rendezvous = _MultiThreadedRendezvous(state, call, None, deadline)
                return state.response, rendezvous
            else:
                return state.response
        else:
>           raise _InactiveRpcError(state)
E           grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
E           	status = StatusCode.UNIMPLEMENTED
E           	details = "Method not found!"
E           	debug_error_string = "{"created":"@1638411902.134236000","description":"Error received from peer ipv6:[::1]:50051","file":"src/core/lib/surface/call.cc","file_line":1063,"grpc_message":"Method not found!","grpc_status":12}"
E           >

../../../../../../venv/lib/python3.7/site-packages/grpc/_channel.py:826: _InactiveRpcError
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/alibaba/work/opensource/ai-flow/ai_flow_plugins/tests/airflow_scheduler_utils.py", line 81, in run_test_fun
    default_namespace="test")
  File "/Users/alibaba/work/opensource/venv/lib/python3.7/site-packages/notification_service/client.py", line 178, in __init__
    response = self.notification_stub.registerClient(request)
  File "/Users/alibaba/work/opensource/venv/lib/python3.7/site-packages/grpc/_channel.py", line 923, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/alibaba/work/opensource/venv/lib/python3.7/site-packages/grpc/_channel.py", line 826, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "{"created":"@1638411907.064991000","description":"Error received from peer ipv6:[::1]:50051","file":"src/core/lib/surface/call.cc","file_line":1063,"grpc_message":"Socket closed","grpc_status":14}"
>

INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.

Assertion failed

Assertion failed
```

### To Reproduce
Steps to reproduce the behavior (if you can):
1. Submit a '...'
3. See error

**Comment by jiangxin369** [comment]
Fixed in https://github.com/flink-extended/ai-flow/pull/197
