### ISSUE TITLE
Task failed caused by database UK error

### ISSUE THREAD

**Issue by jiangxin369** [flink-extended/ai-flow#247]
### Describe the bug
Task instance runs twice so that it will insert 2 rows into database and cause task failed.

### To Reproduce
Steps to reproduce the behavior (if you can):
1. Submit a '...'
3. See error

### Additional context
```
*** Reading local file: /Users/alibaba/airflow/logs/demo.action_on_status/task_3/2022-01-06T06:36:18.576249+00:00/2_1.log
[2022-01-06 14:37:03,596] {taskinstance.py:869} INFO - Dependencies all met for <TaskInstance: demo.action_on_status.task_3 2022-01-06T06:36:18.576249+00:00 [queued]>
[2022-01-06 14:37:03,596] {taskinstance.py:869} INFO - Dependencies all met for <TaskInstance: demo.action_on_status.task_3 2022-01-06T06:36:18.576249+00:00 [queued]>
[2022-01-06 14:37:03,596] {taskinstance.py:1060} INFO - 
--------------------------------------------------------------------------------
[2022-01-06 14:37:03,596] {taskinstance.py:1061} INFO - Starting attempt 1 of 1
[2022-01-06 14:37:03,596] {taskinstance.py:1062} INFO - 
--------------------------------------------------------------------------------
[2022-01-06 14:37:03,597] {taskinstance.py:869} INFO - Dependencies all met for <TaskInstance: demo.action_on_status.task_3 2022-01-06T06:36:18.576249+00:00 [queued]>
[2022-01-06 14:37:03,597] {taskinstance.py:869} INFO - Dependencies all met for <TaskInstance: demo.action_on_status.task_3 2022-01-06T06:36:18.576249+00:00 [queued]>
[2022-01-06 14:37:03,597] {taskinstance.py:1060} INFO - 
--------------------------------------------------------------------------------
[2022-01-06 14:37:03,598] {taskinstance.py:1061} INFO - Starting attempt 1 of 1
[2022-01-06 14:37:03,598] {taskinstance.py:1062} INFO - 
--------------------------------------------------------------------------------
[2022-01-06 14:37:03,602] {taskinstance.py:1081} INFO - Executing <Task(AIFlowOperator): task_3> on 2022-01-06T06:36:18.576249+00:00
[2022-01-06 14:37:03,607] {taskinstance.py:1081} INFO - Executing <Task(AIFlowOperator): task_3> on 2022-01-06T06:36:18.576249+00:00
[2022-01-06 14:37:03,608] {local_task_job.py:157} INFO - LocalTaskJob sending event: key:action_on_status.task_3, value:running, type:TASK_STATUS_CHANGED, version:None, create_time:1641451023602, context: {"task_id": "task_3", "dag_id": "demo.action_on_status", "execution_date": "2022-01-06T06:36:18.576249Z", "state": "running", "try_number": 1, "create_time": 1641451023602}, namespace: demo, sender: task_3
[2022-01-06 14:37:03,615] {local_task_job.py:157} INFO - LocalTaskJob sending event: key:action_on_status.task_3, value:running, type:TASK_STATUS_CHANGED, version:None, create_time:1641451023607, context: {"task_id": "task_3", "dag_id": "demo.action_on_status", "execution_date": "2022-01-06T06:36:18.576249Z", "state": "running", "try_number": 1, "create_time": 1641451023607}, namespace: demo, sender: task_3
[2022-01-06 14:37:03,619] {client.py:199} INFO - The notification client:NotificationClient(id=3465, namespace=demo, sender=task_3, server_uri=127.0.0.1:50052, properties={}) has been closed.
[2022-01-06 14:37:03,622] {standard_task_runner.py:51} INFO - Started process 37687 to run task
[2022-01-06 14:37:03,631] {client.py:199} INFO - The notification client:NotificationClient(id=3466, namespace=demo, sender=task_3, server_uri=127.0.0.1:50052, properties={}) has been closed.
[2022-01-06 14:37:03,629] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'demo.action_on_status', 'task_3', '2022-01-06T06:36:18.576249+00:00', '--job-id', '11', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/demo.action_on_status.py', '--cfg-path', '/var/folders/b0/rv05qnd128vd9d4569g62md00000gp/T/tmpz75p9geb', '--notification-server-uri', '127.0.0.1:50052']
[2022-01-06 14:37:03,632] {standard_task_runner.py:76} INFO - Job 11: Subtask task_3
[2022-01-06 14:37:03,634] {standard_task_runner.py:51} INFO - Started process 37688 to run task
[2022-01-06 14:37:03,642] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'demo.action_on_status', 'task_3', '2022-01-06T06:36:18.576249+00:00', '--job-id', '12', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/demo.action_on_status.py', '--cfg-path', '/var/folders/b0/rv05qnd128vd9d4569g62md00000gp/T/tmplatq8g9u', '--notification-server-uri', '127.0.0.1:50052']
[2022-01-06 14:37:03,644] {standard_task_runner.py:76} INFO - Job 12: Subtask task_3
[2022-01-06 14:37:03,646] {configuration.py:240} WARNING - SQLite is only meant to be used for testing. SQLite is strongly discouraged in production.
[2022-01-06 14:37:03,657] {configuration.py:240} WARNING - SQLite is only meant to be used for testing. SQLite is strongly discouraged in production.
[2022-01-06 14:37:03,679] {logging_mixin.py:103} INFO - Running <TaskInstance: demo.action_on_status.task_3 2022-01-06T06:36:18.576249+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2022-01-06 14:37:03,685] {logging_mixin.py:103} INFO - Running <TaskInstance: demo.action_on_status.task_3 2022-01-06T06:36:18.576249+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2022-01-06 14:37:03,709] {taskinstance.py:1344} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=demo.action_on_status
AIRFLOW_CTX_TASK_ID=task_3
AIRFLOW_CTX_EXECUTION_DATE=2022-01-06T06:36:18.576249+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-06T06:36:18.576249+00:00
[2022-01-06 14:37:03,714] {taskinstance.py:1344} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=demo.action_on_status
AIRFLOW_CTX_TASK_ID=task_3
AIRFLOW_CTX_EXECUTION_DATE=2022-01-06T06:36:18.576249+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-06T06:36:18.576249+00:00
[2022-01-06 14:37:03,717] {ai_flow_operator.py:136} INFO - project_path:/tmp/action_on_status/workflow_action_on_status_2d6978ba420d4f27e64e5c3a07daa090/demo
[2022-01-06 14:37:03,720] {ai_flow_operator.py:136} INFO - project_path:/tmp/action_on_status/workflow_action_on_status_2d6978ba420d4f27e64e5c3a07daa090/demo
[2022-01-06 14:37:03,721] {ai_flow_operator.py:144} INFO - working dir: /tmp/action_on_status/workflow_action_on_status_2d6978ba420d4f27e64e5c3a07daa090/demo/temp
[2022-01-06 14:37:03,724] {ai_flow_operator.py:154} INFO - context:{'conf': <airflow.configuration.AirflowConfigParser object at 0x7fb5e2e312d0>, 'dag': <DAG: demo.action_on_status>, 'dag_run': <DagRun demo.action_on_status @ 2022-01-06 06:36:18.576249+00:00: manual__2022-01-06T06:36:18.576249+00:00, externally triggered: True>, 'ds': '2022-01-06', 'ds_nodash': '20220106', 'execution_date': DateTime(2022, 1, 6, 6, 36, 18, 576249, tzinfo=Timezone('+00:00')), 'inlets': [], 'macros': <module 'airflow.macros' from '/Users/alibaba/work/opensource/venv/lib/python3.7/site-packages/airflow/macros/__init__.py'>, 'next_ds': '2022-01-06', 'next_ds_nodash': '20220106', 'next_execution_date': DateTime(2022, 1, 6, 6, 36, 18, 576249, tzinfo=Timezone('+00:00')), 'outlets': [], 'params': {}, 'prev_ds': '2022-01-06', 'prev_ds_nodash': '20220106', 'prev_execution_date': DateTime(2022, 1, 6, 6, 36, 18, 576249, tzinfo=Timezone('+00:00')), 'prev_execution_date_success': <Proxy at 0x7fb5e96210f0 with factory <function TaskInstance.get_template_context.<locals>.<lambda> at 0x7fb5e9638950>>, 'prev_start_date_success': <Proxy at 0x7fb5e9621550 with factory <function TaskInstance.get_template_context.<locals>.<lambda> at 0x7fb5e964db00>>, 'run_id': 'manual__2022-01-06T06:36:18.576249+00:00', 'task': <Task(AIFlowOperator): task_3>, 'task_instance': <TaskInstance: demo.action_on_status.task_3 2022-01-06T06:36:18.576249+00:00 [running]>, 'task_instance_key_str': 'demo.action_on_status__task_3__20220106', 'test_mode': False, 'ti': <TaskInstance: demo.action_on_status.task_3 2022-01-06T06:36:18.576249+00:00 [running]>, 'te': <TaskExecution: demo.action_on_status.task_3 2022-01-06 06:36:18.576249+00:00 2 [running]>, 'notification_server_uri': '127.0.0.1:50052', 'tomorrow_ds': '2022-01-07', 'tomorrow_ds_nodash': '20220107', 'ts': '2022-01-06T06:36:18.576249+00:00', 'ts_nodash': '20220106T063618', 'ts_nodash_with_tz': '20220106T063618.576249+0000', 'var': {'json': None, 'value': None}, 'yesterday_ds': '2022-01-05', 'yesterday_ds_nodash': '20220105'}
[2022-01-06 14:37:03,724] {ai_flow_operator.py:144} INFO - working dir: /tmp/action_on_status/workflow_action_on_status_2d6978ba420d4f27e64e5c3a07daa090/demo/temp
[2022-01-06 14:37:03,724] {ai_flow_operator.py:158} INFO - submitting job with job_runtime_env: {'_working_dir': '/tmp/action_on_status/workflow_action_on_status_2d6978ba420d4f27e64e5c3a07daa090/demo/temp/action_on_status/task_3/20220106143703', '_job_execution_info': {"__af_object_type__": "jsonable", "__class__": "JobExecutionInfo", "__module__": "ai_flow.plugin_interface.scheduler_interface", "_end_date": "0", "_execution_label": null, "_job_execution_id": "1", "_job_name": "task_3", "_properties": {}, "_start_date": "1641451023597", "_status": "running", "_workflow_execution": {"__af_object_type__": "jsonable", "__class__": "WorkflowExecutionInfo", "__module__": "ai_flow.plugin_interface.scheduler_interface", "_context": null, "_end_date": "0", "_properties": {}, "_start_date": "1641450978577", "_status": "running", "_workflow_execution_id": "2", "_workflow_info": {"__af_object_type__": "jsonable", "__class__": "WorkflowInfo", "__module__": "ai_flow.plugin_interface.scheduler_interface", "_namespace": "demo", "_properties": {}, "_scheduling_rules": null, "_workflow_name": "action_on_status"}}}, '_workflow_config': None, '_project_config': None}
[2022-01-06 14:37:03,725] {ai_flow_operator.py:154} INFO - context:{'conf': <airflow.configuration.AirflowConfigParser object at 0x7f96c4086ed0>, 'dag': <DAG: demo.action_on_status>, 'dag_run': <DagRun demo.action_on_status @ 2022-01-06 06:36:18.576249+00:00: manual__2022-01-06T06:36:18.576249+00:00, externally triggered: True>, 'ds': '2022-01-06', 'ds_nodash': '20220106', 'execution_date': DateTime(2022, 1, 6, 6, 36, 18, 576249, tzinfo=Timezone('+00:00')), 'inlets': [], 'macros': <module 'airflow.macros' from '/Users/alibaba/work/opensource/venv/lib/python3.7/site-packages/airflow/macros/__init__.py'>, 'next_ds': '2022-01-06', 'next_ds_nodash': '20220106', 'next_execution_date': DateTime(2022, 1, 6, 6, 36, 18, 576249, tzinfo=Timezone('+00:00')), 'outlets': [], 'params': {}, 'prev_ds': '2022-01-06', 'prev_ds_nodash': '20220106', 'prev_execution_date': DateTime(2022, 1, 6, 6, 36, 18, 576249, tzinfo=Timezone('+00:00')), 'prev_execution_date_success': <Proxy at 0x7f96ca3a9280 with factory <function TaskInstance.get_template_context.<locals>.<lambda> at 0x7f96cb438950>>, 'prev_start_date_success': <Proxy at 0x7f96cb445e10 with factory <function TaskInstance.get_template_context.<locals>.<lambda> at 0x7f96cb44eb00>>, 'run_id': 'manual__2022-01-06T06:36:18.576249+00:00', 'task': <Task(AIFlowOperator): task_3>, 'task_instance': <TaskInstance: demo.action_on_status.task_3 2022-01-06T06:36:18.576249+00:00 [running]>, 'task_instance_key_str': 'demo.action_on_status__task_3__20220106', 'test_mode': False, 'ti': <TaskInstance: demo.action_on_status.task_3 2022-01-06T06:36:18.576249+00:00 [running]>, 'te': <TaskExecution: demo.action_on_status.task_3 2022-01-06 06:36:18.576249+00:00 2 [running]>, 'notification_server_uri': '127.0.0.1:50052', 'tomorrow_ds': '2022-01-07', 'tomorrow_ds_nodash': '20220107', 'ts': '2022-01-06T06:36:18.576249+00:00', 'ts_nodash': '20220106T063618', 'ts_nodash_with_tz': '20220106T063618.576249+0000', 'var': {'json': None, 'value': None}, 'yesterday_ds': '2022-01-05', 'yesterday_ds_nodash': '20220105'}
[2022-01-06 14:37:03,726] {ai_flow_operator.py:158} INFO - submitting job with job_runtime_env: {'_working_dir': '/tmp/action_on_status/workflow_action_on_status_2d6978ba420d4f27e64e5c3a07daa090/demo/temp/action_on_status/task_3/20220106143703', '_job_execution_info': {"__af_object_type__": "jsonable", "__class__": "JobExecutionInfo", "__module__": "ai_flow.plugin_interface.scheduler_interface", "_end_date": "0", "_execution_label": null, "_job_execution_id": "1", "_job_name": "task_3", "_properties": {}, "_start_date": "1641451023597", "_status": "running", "_workflow_execution": {"__af_object_type__": "jsonable", "__class__": "WorkflowExecutionInfo", "__module__": "ai_flow.plugin_interface.scheduler_interface", "_context": null, "_end_date": "0", "_properties": {}, "_start_date": "1641450978577", "_status": "running", "_workflow_execution_id": "2", "_workflow_info": {"__af_object_type__": "jsonable", "__class__": "WorkflowInfo", "__module__": "ai_flow.plugin_interface.scheduler_interface", "_namespace": "demo", "_properties": {}, "_scheduling_rules": null, "_workflow_name": "action_on_status"}}}, '_workflow_config': None, '_project_config': None}
[2022-01-06 14:37:03,726] {bash_job_plugin.py:105} INFO - Running command: echo hello
[2022-01-06 14:37:03,726] {bash_job_plugin.py:105} INFO - Running command: echo hello
[2022-01-06 14:37:03,733] {bash_job_plugin.py:115} INFO - Process pid: 37689
[2022-01-06 14:37:03,734] {bash_job_plugin.py:115} INFO - Process pid: 37690
[2022-01-06 14:37:03,735] {ai_flow_operator.py:162} INFO - Starting execution label report thread.
[2022-01-06 14:37:03,735] {ai_flow_operator.py:162} INFO - Starting execution label report thread.
[2022-01-06 14:37:03,736] {bash_job_plugin.py:124} INFO - AINode_2 Output:
[2022-01-06 14:37:03,736] {bash_job_plugin.py:124} INFO - AINode_2 Output:
[2022-01-06 14:37:03,737] {bash_job_plugin.py:129} INFO - hello
[2022-01-06 14:37:03,737] {bash_job_plugin.py:129} INFO - hello
[2022-01-06 14:37:03,737] {bash_job_plugin.py:133} INFO - Command exited with return code 0
[2022-01-06 14:37:03,737] {bash_job_plugin.py:133} INFO - Command exited with return code 0
[2022-01-06 14:37:03,738] {ai_flow_operator.py:183} INFO - Stopping execution label report thread.
[2022-01-06 14:37:03,738] {ai_flow_operator.py:183} INFO - Stopping execution label report thread.
[2022-01-06 14:37:03,756] {taskinstance.py:1254} INFO - Marking task as SUCCESS. dag_id=demo.action_on_status, task_id=task_3, execution_date=20220106T063618, start_date=20220106T063703, end_date=20220106T063703
[2022-01-06 14:37:03,753] {taskinstance.py:1508} ERROR - (sqlite3.IntegrityError) UNIQUE constraint failed: xcom.dag_id, xcom.task_id, xcom.key, xcom.execution_date
[SQL: INSERT INTO xcom ("key", value, timestamp, execution_date, task_id, dag_id) VALUES (?, ?, ?, ?, ?, ?)]
[parameters: ('return_value', <memory at 0x7f96cb40b6d0>, '2022-01-06 06:37:03.747820', '2022-01-06 06:36:18.576249', 'task_3', 'demo.action_on_status')]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
Traceback (most recent call last):
  File "/Users/alibaba/work/opensource/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/Users/alibaba/work/opensource/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: xcom.dag_id, xcom.task_id, xcom.key, xcom.execution_date

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/alibaba/work/opensource/venv/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1191, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/alibaba/work/opensource/venv/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1372, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/alibaba/work/opensource/venv/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1415, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/Users/alibaba/work/opensource/venv/lib/python3.7/site-packages/airflow/utils/session.py", line 65, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/alibaba/work/opensource/venv/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1952, in xcom_push
    session=session,
  File "/Users/alibaba/work/opensource/venv/lib/python3.7/site-packages/airflow/utils/session.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/Users/alibaba/work/opensource/venv/lib/python3.7/site-packages/airflow/models/xcom.py", line 100, in set
    session.commit()
  File "/Users/alibaba/work/opensource/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1046, in commit
    self.transaction.commit()
  File "/Users/alibaba/work/opensource/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 504, in commit
    self._prepare_impl()
  File "/Users/alibaba/work/opensource/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 483, in _prepare_impl
    self.session.flush()
  File "/Users/alibaba/work/opensource/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2540, in flush
    self._flush(objects)
  File "/Users/alibaba/work/opensource/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2682, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/alibaba/work/opensource/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/Users/alibaba/work/opensource/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/Users/alibaba/work/opensource/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2642, in _flush
    flush_context.execute()
  File "/Users/alibaba/work/opensource/venv/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/Users/alibaba/work/opensource/venv/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/Users/alibaba/work/opensource/venv/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/Users/alibaba/work/opensource/venv/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1083, in _emit_insert_statements
    c = cached_connections[connection].execute(statement, multiparams)
  File "/Users/alibaba/work/opensource/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/Users/alibaba/work/opensource/venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/alibaba/work/opensource/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "/Users/alibaba/work/opensource/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/Users/alibaba/work/opensource/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/Users/alibaba/work/opensource/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/Users/alibaba/work/opensource/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/Users/alibaba/work/opensource/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: xcom.dag_id, xcom.task_id, xcom.key, xcom.execution_date
```

**Comment by jiangxin369** [comment]
```
[2022-01-06 15:19:50,787] {event_based_scheduler_job.py:130} DEBUG - Event: key:action_on_status.task_2, value:killed, ty
pe:TASK_STATUS_CHANGED, version:None, create_time:1641453585671, context: {"task_id": "task_2", "dag_id": "demo.action_on
_status", "execution_date": "2022-01-06T07:19:07.569191Z", "state": "killed", "try_number": 1, "create_time": 16414535856
71}, namespace: demo, sender: task_2
[2022-01-06 15:19:50,827] {event_based_scheduler_job.py:130} DEBUG - Event: key:action_on_status.task_2, value:killed, ty
pe:TASK_STATUS_CHANGED, version:None, create_time:1641453590777, context: {"task_id": "task_2", "dag_id": "demo.action_on
_status", "execution_date": "2022-01-06T07:19:07.569191Z", "state": "killed", "try_number": 1, "create_time": 16414535907
77}, namespace: demo, sender: task_2
```

Seems that the event (TASK_STATUS_CHANGED, value=KILLED ) is sent twice, and the downstream task depends on this event to restart itself, so it runs twice
